version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    hostname: hostname-mongodb
    ports:
      - "27026:27026"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: