// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/user/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IAddUserUseCase is an autogenerated mock type for the IAddUserUseCase type
type IAddUserUseCase struct {
	mock.Mock
}

// Add provides a mock function with given fields: c, req
func (_m *IAddUserUseCase) Add(c context.Context, req *request.ReqAddUser) error {
	ret := _m.Called(c, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqAddUser) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAddUserUseCase creates a new instance of IAddUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAddUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAddUserUseCase {
	mock := &IAddUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
