// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IGetsUserHandler is an autogenerated mock type for the IGetsUserHandler type
type IGetsUserHandler struct {
	mock.Mock
}

// Gets provides a mock function with given fields: c
func (_m *IGetsUserHandler) Gets(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIGetsUserHandler creates a new instance of IGetsUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetsUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetsUserHandler {
	mock := &IGetsUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
